# Generated by Django 4.2 on 2023-11-14 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_publish_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publish_date2',
        ),
    ]
